### ISSUE TITLE
LightProvider 도커버전 접속 문의

### ISSUE THREAD

**Issue by ghost** [segunlee/LightProviderNest#1]
안녕하세요

시놀에 도커로 LightProvider을 설치하고 사용해보려고 합니다.

1. 접속주소는 시놀 ddns로 접속하려고 하는데 이렇게 url을 입력하면 로딩표시만 뜨고 접속이 안됩니다.
다른 설정이 필요한지 궁금합니다.   방화벽의 포트 허용은 이미 해두었습니다.

2.  로컬에서 ip로 접속은 되었습니다. 그러나 에러가 발생하면서 파일 열람이 되지 않습니다. 

![image](https://user-images.githubusercontent.com/82558524/114886817-d6943780-9e42-11eb-873b-e8b2a930505f.png)

2가지 답변을 부탁드립니다.

**Comment by segunlee** [comment]
안녕하세요 아마도 포트번호에 오류가 발생한 것 같습니다. 
앱 내 문의하기를 통해 로그파일도 첨부하여 보내주시면 문의 답변드리겠습니다.

**Comment by segunlee** [comment]
@stoneiron79 보내주신 로그 확인했습니다. 
우선 http를 안붙이고 하셔야 정상적인 URL로 접속을 시도합니다.
로그상 나와 있는 서버 포트 오픈 체크를 해봤는데 포트가 닫혀있네요.
공유기 및 나스에서 포트 설정 확인해보셔야 될 것 같습니다

**Comment by ghost** [comment]
이제 잘 작동합니다. 좋은 프로그램에 좋은기능 업데이트 감사합니다.
